
//GETTERS
const ALL_SHOES = "ALL_SHOES";
const GET_FIRST_FOUR_SHOES = "GET_FIRST_FOUR_SHOES";
const GET_SHOE_BY_ID = "GET_SHOE_BY_ID"
const GET_FOUR_JORDAN_SNEAKERS = "GET_FOUR_JORDAN_SNEAKERS"
const UNIQUE_BRANDS = "UNIQUE_BRANDS"
const INCLUDE_SHOE_BY_BRAND = "INCLUDE_SHOE_BY_BRAND"
const FILTERED_SHOES = "FILTERED_SHOES";